### ISSUE TITLE
Issue 1: Web Reverse Proxy Role

### ISSUE THREAD

**Issue by AhmadMWaddah** [AhmadMWaddah/linux-automation-infrastructure-Prjct_02#3]
### 🎯 Goal
Create and apply an Ansible role that sets up NGINX as a reverse proxy on a VM.

### 💻 Machines Used
  - WebServVM

### 📝 Tasks
- [ ] Create a role: `roles/reverse_proxy/`
- [ ] Install and configure NGINX as reverse proxy
- [ ] Add support for forwarding traffic to backend
- [ ] Set up firewall rules

### 📚 References
- `ansible-galaxy init`, NGINX Docs  
- https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-as-a-reverse-proxy-on-centos-7

### ⏱️ Estimated Time
2 hours

### 📁 Snippet
```yaml
- name: Install NGINX
  dnf:
    name: nginx
    state: present

- name: Deploy reverse proxy config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

**Comment by AhmadMWaddah** [comment]
### 💻 Machines Used
  - WebServVM

### 📝 Completed Tasks
  - [x] Create a role: `roles/reverse_proxy/`
    - Created the Reverse Proxy with `ansible-galaxy init roles/reverse_proxy` it will created the role directory structure.
    ```
      roles/
        └── reverse_proxy
          ├── defaults
            └── main.yml
          ├── files
          ├── handlers
            └── main.yml
          ├── meta
            └── main.yml
          ├── nginx.conf.j2
          ├── README.md
          ├── tasks
            └── main.yml
          ├── templates
          ├── tests
          ├── inventory
            └── test.yml
          └── vars
            └── main.yml

    ```

  - [x] Install and configure NGINX as reverse proxy
    - Added a file `roles/tasks/main.yml` [main.yml](https://github.com/AhmadMWaddah/linux-automation-infrastructure-Prjct_02/blob/master/roles/reverse_proxy/tasks/main.yml) for tasks role reverse proxy.
    ```
      ---
      - name: Install NGINX
        dnf:
          name: nginx
          state: present

      - name: Copy custom NGINX config
        template:
          src: nginx.conf.j2
          dest: /etc/nginx/nginx.conf
        notify: Restart nginx

      - name: Start and enable NGINX
        systemd:
          name: nginx
          state: started
          enabled: true

      - name: Allow HTTP traffic through firewall
        firewalld:
          service: http
          permanent: true
          state: enabled
          immediate: true

    ```
    - Added Template for NGINX Configurations `roles/reverse_proxy/templates/nginx.conf.j2` [NGINX Config File](https://github.com/AhmadMWaddah/linux-automation-infrastructure-Prjct_02/blob/master/roles/reverse_proxy/templates/nginx.conf.j2)
    ```
      events {}

      http {
        server {
          listen 8080;
          location / {
            proxy_pass http://{{ backend_ip }}:{{ backend_port }};
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
        }
      }

    ```

- [x] Add support for forwarding traffic to backend
  - Already handled in [NGINX Config File](https://github.com/AhmadMWaddah/linux-automation-infrastructure-Prjct_02/blob/master/roles/reverse_proxy/templates/nginx.conf.j2) `proxy_pass http://{{ backend_ip }}:{{ backend_port }};`

- [x] Set up firewall rules
  - Ensure `firewalld` is running on `WebServVM` using `sudo systemctl enable --now firewalld`

- [x] Adding Playbook to Run the Role
  - Created the playbook reverse proxyin that path `playbooks/reverse-proxy.yml` [reverse-proxy](https://github.com/AhmadMWaddah/linux-automation-infrastructure-Prjct_02/blob/master/playbooks/reverse-proxy.yml)
  
  ```
    - name: Set up NGINX reverse proxy on WebServVM
      hosts: WebServVM
      become: true
      roles:
        - reverse_proxy
  ```

  - run playbook
    `ansible-playbook -i inventories/hosts.ini playbooks/reverse-proxy.yml`


### Common Bugs & Fixes

#### NGINX Failed to Start (Port 80 in Use)

  - **Error:**
    ```
    nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
    ```
  -  **Fix Option 1 - Stop Conflicting Service:**

    - Check what's using port 80:
      ```
      sudo lsof -i :80
      ```

    - Stop the conflicting service (usually Apache):
      ```
      sudo systemctl stop httpd
      sudo systemctl disable httpd
      ```

  - **Fix Option 2 - Change NGINX Port:**

    - Change `listen 80;` to `listen 8080;` in `nginx.conf.j2` and allow the new port in your firewall.

#### Missing sudo Password Error

  - **Fix - Allow Passwordless sudo:**

    - Edit the sudoers file:
    ```
    sudo visudo
    ```

    - Add the following line (replace `ServUserOne` with your username):
    ```
    ServUserOne ALL=(ALL) NOPASSWD: ALL
    ```

#### SSH or Ansible Connectivity Issues

  - **Troubleshooting Steps:**

    - Ensure the following are correctly configured:

      - `ansible_user`, `ansible_port`, and `ansible_ssh_private_key_file` are properly set in `inventories/hosts.ini`
      - The specified user exists on the target VM
      - SSH keys are properly configured in the user's `~/.ssh/authorized_keys`
      - SSH configuration and Ansible configuration are not conflicting with each other

  - **Common checks:**
    ```
    # Test SSH connection manually
    ssh -i /path/to/private/key username@hostname -p port
    ```
    ```
    # Test Ansible connectivity
    ansible all -m ping -i inventories/hosts.ini
    ```
