### ISSUE TITLE
Issue 1: Add Linting and Syntax Checks

### ISSUE THREAD

**Issue by AhmadMWaddah** [AhmadMWaddah/linux-automation-infrastructure-Prjct_02#7]
### 🎯 Goal
Integrate linting for Ansible playbooks into GitHub Actions CI pipeline.

### 💻 Machines Used
  - No Actual VMs.

### 📝 Tasks
- [ ] Set up `.github/workflows/lint.yml`
- [ ] Add `ansible-lint` job
- [ ] Fail PR if linting fails

### 📚 References
- https://github.com/ansible/ansible-lint  
- GitHub Actions docs

### ⏱️ Estimated Time
45 minutes

### 📁 Snippet
```yaml
- name: Lint
  run: |
    pip install ansible-lint
    ansible-lint .

**Comment by AhmadMWaddah** [comment]
### 💻 Machines Used
  - No Actual VMs.

### 📝 Completed Tasks
- [x] Set up `.github/workflows/lint.yml`
  - Created the [File Attached](https://github.com/AhmadMWaddah/linux-automation-infrastructure-Prjct_02/blob/master/.github/workflows/lint.yml) using command `mkdir -p .github/workflows`

- [x] Add `ansible-lint` job
  - Added the Ansible Linting Configurations as follows.
  ```
  name: Ansible Lint CI

  on:
    push:
      paths:
        - '**.yml'
        - '**.yaml'
        - '**/roles/**'
        - 'playbooks/**'
    pull_request:
      paths:
        - '**.yml'
        - '**.yaml'
        - '**/roles/**'
        - 'playbooks/**'
  
  jobs:
    lint:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
  
        - name: Install Ansible and ansible-lint
          run: |
            python -m pip install --upgrade pip
            pip install ansible ansible-lint
  
        - name: Run ansible-lint
          run: |
            ansible-lint .
  ```

  - Test the Linting Actions in GitHub Repo.
  After `commit` and `push` to your repo you will check on the GitHub Repo `Action` tab there will be an action of linting available as the [ScreenShot](https://github.com/AhmadMWaddah/linux-automation-infrastructure-Prjct_02/blob/master/GitHub%20Actions%20Linting.png).

- [x] Fail PR if linting fails
  - I Will Enforce on Pull Requests by Enable CI checks in GitHub by following the steps below
  > Settings → Branches → Add branch protection rule → Require status checks to pass before merging.

  then select your lint workflow, [ScreenShot](https://github.com/AhmadMWaddah/linux-automation-infrastructure-Prjct_02/blob/master/Branch%20Protection%20Rule.png).
